### ISSUE TITLE
Support EKS Cluster and Nodegroup names with underscore (_)

### ISSUE THREAD

**Issue by praveen-rafay** [RafaySystems/roadmap#102]
Currenlty Import+Managed workflow fails when EKS cluster name is having underscore. 

Cluster & nodegroup name with underscore.

- > EKS nodegroup name, takeover will fail
- > EKS Cluster name, creation of new nodegroup will fail due to cloudformation validation.

**Comment by atreyamohan** [comment]
https://docs.rafay.co/releasenotes/2023/may/#v125-saas
